easy_admin:
  entities:
    Header:
      class: App\Entity\Page\Header\Header
      list:
        fields:
          - id
          - heroTitle
          - heroSubtitle
          - { 
            property: 'headerImageImage', 
            type: 'image', 
            base_path: '%app.page.header_image%' 
            }
          - { 
            property: 'headerAvatarImage', 
            type: 'image', 
            base_path: '%app.page.header_avatar%' 
            }
      form:
        fields:
          - heroTitle
          - heroSubtitle
          - {
            property: 'heroImage',
            type: 'easyadmin_autocomplete', 
            type_options: { class: 'App\Entity\Page\Header\HeaderImage' }
            }
          - {
            property: 'headerAvatar',
            type: 'easyadmin_autocomplete', 
            type_options: { class: 'App\Entity\Page\Header\HeaderAvatar' }
            }
    
    HeaderImage:
      class: App\Entity\Page\Header\HeaderImage
      label: Header Image
      list:
        fields:
          - id
          - {
            property: name,
            type: 'string'
            }
          - { 
            property: 'image', 
            type: 'image', 
            base_path: '%app.page.header_image%' 
            }
      form:
        fields:
          - { 
            property: 'imageFile', 
            type: 'vich_image' 
            }
    
    HeaderAvatar:
      class: App\Entity\Page\Header\HeaderAvatar
      label: Header Avatar
      list:
        fields:
          - id
          - {
            property: name,
            type: 'string'
            }
          - { 
            property: 'image', 
            type: 'image', 
            base_path: '%app.page.header_avatar%' 
            }
      form:
        fields:
          - { 
            property: 'imageFile', 
            type: 'vich_image' 
            }

    Article:
      class: App\Entity\Page\Article\Article
      list:
        fields:
          - id
          - title
          - createdAt
          - updatedAt
          - publishAt
      form:
        fields:
          - title
          - shortText
          - { 
            property: 'content', 
            type: 'fos_ckeditor' 
            }
          - {
            property: publishAt,
            type: datetime
            }

    User:
      class: App\Entity\User\User
      list:
        fields:
          - id
          - username
          - name
          - surname
      form:
        fields:
          - name
          - surname


