easy_admin:
  entities:
    Header:
      class: App\Entity\Page\Header\Header
      list:
        fields:
          - id
          - heroTitle
          - heroSubtitle
          - { property: 'headerImageImage', type: 'image', base_path: '%app.page.header_image%' }
          - { property: 'headerAvatarImage', type: 'image', base_path: '%app.page.header_avatar%' }
      show:
        fields:
          - id
          - heroTitle
          - heroSubtitle
          - { property: 'headerImageImage', type: 'image', base_path: '%app.page.header_image%' }
          - { property: 'headerAvatarImage', type: 'image', base_path: '%app.page.header_avatar%' }
      form:
        fields:
          - heroTitle
          - heroSubtitle
          - {
            property: 'heroImage',
            type: 'easyadmin_autocomplete', 
            type_options: { class: 'App\Entity\Page\Header\HeaderImage' }
            }
          - {
            property: 'headerAvatar',
            type: 'easyadmin_autocomplete', 
            type_options: { class: 'App\Entity\Page\Header\HeaderAvatar' }
            }
    
    HeaderImage:
      class: App\Entity\Page\Header\HeaderImage
      list:
        fields:
          - id
          - { property: 'image', type: 'image', base_path: '%app.page.header_image%' }
      show:
        fields:
          - id
          - { property: 'image', type: 'image', base_path: '%app.page.header_image%' }
      form:
        fields:
          - { property: 'imageFile', type: 'vich_image' }
    
    HeaderAvatar:
      class: App\Entity\Page\Header\HeaderAvatar
      list:
        fields:
          - id
          - { property: 'image', type: 'image', base_path: '%app.page.header_avatar%' }
      show:
        fields:
          - id
          - { property: 'image', type: 'image', base_path: '%app.page.header_avatar%' }
      form:
        fields:
          - { property: 'imageFile', type: 'vich_image' }

    User:
      class: App\Entity\User\User
      list:
        fields:
          - id
          - username
          - name
          - surname
      show:
        fields:
          - id
          - username
          - name
          - surname
      form:
        fields:
          - name
          - surname


