vich_uploader:
    db_driver: orm

    mappings:
        header_images:
            uri_prefix:         '%app.page.header_image%'
            upload_destination: '%kernel.project_dir%/public%app.page.header_image%'

        header_avatars:
            uri_prefix:         '%app.page.header_avatar%'
            upload_destination: '%kernel.project_dir%/public%app.page.header_avatar%'

            
